### ISSUE TITLE
Windows 10: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by LeoSunTL** [bnahill/PyCortexMDebug#56]
Using this project on Windows 10 with Python 3.12.3

When source svd scripts, report errors:

```bash
(gdb) source PyCortexMDebug/cmdebug/svd_gdb.py
Traceback (most recent call last):
  File "c:\users\403283\scoop\apps\xpack-gcc-arm-none-eabi\current\arm-none-eabi\share\gdb/python\gdb\__init__.py", line 147, in _execute_file
    exec(compiled, globals, globals)
  File "PyCortexMDebug/cmdebug/svd_gdb.py", line 23, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by bnahill** [comment]
I think pkg_resources is part of the setuptools package. Try installing that.

**Comment by LeoSunTL** [comment]
Thank you, turns out I have to make gdb to load .gdbinit to make python of gdb to load environments of host PC.
